FROM ubuntu

# Install openssh-server
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y openssh-server

# Set root password
RUN echo 'root:root' | chpasswd

# Set up ssh server configuration accepting root login
RUN mkdir /var/run/sshd && \
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Expose ssh port
EXPOSE 22

# Start ssh server
CMD ['/usr/sbin/sshd', '-D']