FROM ensemblorg/ensembl-hive-sge

RUN sudo useradd -m metascheduler \
    && echo "metascheduler:metascheduler" | sudo chpasswd \
    && sudo mkdir /home/metascheduler/.ssh \
    && sudo chown metascheduler:metascheduler /home/metascheduler/.ssh \
    && sudo chmod 700 /home/metascheduler/.ssh \
    && sudo ssh-keygen -A \
    && sudo sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config \
    && sudo sed -i 's/#PasswordAuthentication no/PasswordAuthentication no/' /etc/ssh/sshd_config \
    && sudo sed -i 's/#AuthorizedKeysFile/AuthorizedKeysFile/' /etc/ssh/sshd_config

COPY id_ed25519.pub /home/metascheduler/.ssh/authorized_keys

EXPOSE 22

CMD ["service", "ssh", "start", "-D", "-d", "-e", "-f", "/etc/ssh/sshd_config"]