name: Pytest on API

on:
    push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: pipenv
    - run: |
        python -m pip install --upgrade pip
        pip install pipenv
        cd api/
        pipenv install --dev
    - name: Run tests
      run: |
        cd api/
        export PYTHONPATH=..
        export TESTING=1
        pipenv shell
        pytest